import Mock from 'mockjs'

let List = []

export default {
    getStaticalData: () => {
        for (let i = 0; i < 7; i++) {
            List.push(
                Mock.mock({
                    苹果:Mock.Random.float(100,8000,0,0),
                    vivo:Mock.Random.float(100,8000,0,0),
                    oppo:Mock.Random.float(100,8000,0,0),
                    魅族:Mock.Random.float(100,8000,0,0),
                    三星:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0),
                })
            )
        }
        return {
            code:20000,
            data:{
                videoData:[
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'苹果',
                        value:5999
                    },
                    {
                        name:'vivo',
                        value:1500
                    },
                    {
                        name:'oppo',
                        value:1999
                    },
                    {
                        name:'魅族',
                        value:3999
                    },
                    {
                        name:'三星',
                        value:6999
                    },
                ],
                userData: [
                    {
                        date:'周一',
                        new:5,
                        active:200
                    },
                    {
                        date:'周二',
                        new:51,
                        active:2100
                    },
                    {
                        date:'周三',
                        new:12,
                        active:200
                    },
                    {
                        date:'周四',
                        new:5,
                        active:2200
                    },
                    {
                        date:'周五',
                        new:52,
                        active:2200
                    },
                    {
                        date:'周六',
                        new:33,
                        active:2001
                    },
                    {
                        date:'周日',
                        new:115,
                        active:2100
                    },
                ],
                orderData:{
                    date:['20230811','20230812','20230813','20230814','20230815','20230816','20230817','20230818',],
                    data:List
                },
                tableData:[
                    {
                        name:'oppo',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:22000
                    },
                    {
                        name:'vivo',
                        todayBuy:100,
                        monthBuy:500,
                        totalBuy:2000
                    },
                    {
                        name:'苹果',
                        todayBuy:5100,
                        monthBuy:31500,
                        totalBuy:220010
                    },
                    {
                        name:'魅族',
                        todayBuy:300,
                        monthBuy:3500,
                        totalBuy:2000
                    },
                    {
                        name:'三星',
                        todayBuy:500,
                        monthBuy:3500,
                        totalBuy:11000
                    },
                    {
                        name:'小米',
                        todayBuy:1500,
                        monthBuy:3500,
                        totalBuy:32000
                    },
                ]
            }
        }
    }
}